# Find MUMPS includes and libraries.
# The following variables are set if MUMPS is found.  If MUMPS is not
# found, MUMPS_FOUND is set to false.
#  ARPACK_FOUND        - True when the MUMPS include directory is found.
#  ARPACK_INCLUDE_DIRS - the path to where the Siconos MUMPS include files are.
#  ARPACK_LIBRARY_DIRS - The path to where the Siconos library files are.
#  ARPACK_LIBRARIES    - The libraries to link against Siconos MUMPS

SET(ARPACK_SEARCH_PATHS ${ARPACK_DIR})

FIND_LIBRARY(ARPACK_LIB NAMES arpack PATHS ${ARPACK_SEARCH_PATHS})
FIND_LIBRARY(PARPACK_LIB NAMES parpack PATHS ${ARPACK_SEARCH_PATHS})
SET(ARPACK_LIBS ${ARPACK_LIB} ${PARPACK_LIB})

SET(ARPACK_FOUND FALSE)
IF (ARPACK_LIB) 
    IF( PARPACK_LIB )
        SET(ARPACK_FOUND TRUE)
    endif()
ENDIF()

IF (ARPACK_FOUND)
    MESSAGE(STATUS "Found Arpack : ${ARPACK_LIBS}")
    IF (NOT ARPACK_LIB_FIND_QUIETLY)
        GET_FILENAME_COMPONENT(ARPACK_PATH ${ARPACK_LIB} PATH CACHE)
        SET(ARPACK_INCLUDE_DIR ${ARPACK_PATH}/../include CACHE FILEPATH "ARPACK include directory.")
    ENDIF (NOT ARPACK_LIB_FIND_QUIETLY)
ELSE(ARPACK_FOUND)
    IF (ARPACK_LIB_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find Arpack")
    ENDIF (ARPACK_LIB_FIND_REQUIRED)
ENDIF (ARPACK_FOUND)

set(ARPACK_INCLUDE_DIRS ${ARPACK_INCLUDE_DIR})
set(ARPACK_LIBRARIES ${ARPACK_LIBS})

MARK_AS_ADVANCED(ARPACK_INCLUDE_DIR ARPACK_LIBS ARPACK_INCLUDE_DIRS ARPACK_LIBRARIES)
